### ISSUE TITLE
Key error generated from withiin docker sentry image

### ISSUE THREAD

**Issue by zhiyong80** [getsentry/docker-sentry#85] opened 2016-08-28 17:02 UTC
I noticed a rather weird error in one of my projects, it seems come out from nowhere.

KeyErrordjango.core.handlers.wsgi in __init__
erroru'REQUEST_METHOD'

Tags
    level = error
    server_name = 55373efd9140
    site = example.com
    url = http://55373efd9140:9000/
    user = ip:139.162.209.35

Message
KeyError: u'REQUEST_METHOD'

xception(most recent call last)
KeyError

u'REQUEST_METHOD'
    Called from: raven/middleware.py in __call__
    sentry/wsgi.py in __call__ at line 40

    responses.
    Note: this was added natively into Django 1.8, so if by some reason,
    we upgraded, this wouldn't be relevant anymore."""
    def __call__(self, environ, start_response):
        response = super(FileWrapperWSGIHandler, self).__call__(environ, start_response)
        if hasattr(response, 'streaming') and response.streaming:
            try:
                **response = environ['wsgi.file_wrapper'](response.streaming_content)**
            except KeyError:
                # In our case, we're shipping with uwsgi, so it's safer to assume

environ
{'REMOTE_ADDR': '139.162.209.35', 'SCRIPT_NAME': u'', 'SERVER_NAME': '55373efd9140', 'SERVER_PORT': '9000', 'uwsgi.core': 0, 'uwsgi.node': '55373efd9140', 'uwsgi.version': '2.0.13.1', 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f5ccd667810>, 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>, 'wsgi.input': <uwsgi._Input object at 0x7f5ccad429d8>, 'wsgi.multiprocess': True, 'wsgi.multithread': True, 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.version': [1, 0], u'PATH_INFO': u'/'}

self	<sentry.wsgi.FileWrapperWSGIHandler object at 0x7f5ccd6e6e90>
start_response	
<built-in function uwsgi_spit>

User
IP Address	139.162.209.35

Additional Data
sys.argv	['uwsgi']

Packages
python	2.7.12
sentry	8.6.0
A screen shot is also attached at the end. 

At the beginning I thought my DSN might have been used by some unknown party, but then I realized this most likely is generated by sentry itself. It seems to connecting to a remote server then something happened.

Not sure the nature of this issue, just want to reported in case it is something that can/need be addressed.

Thanks.

![sentry-docker-internal-error](https://cloud.githubusercontent.com/assets/13650939/18035219/1364be6e-6d06-11e6-993e-7224be351c5f.png)

**Comment by mattrobenolt** [comment] 2016-08-28 17:55
Hmm, that is very very odd.

Did this just happen the one time? Or does it regularly happen?

**Comment by mattrobenolt** [comment] 2016-08-28 17:56
Oh, and can you share the stack trace under the "Raw" tab?

**Comment by mattrobenolt** [comment] 2016-08-28 17:59
I don't understand how you'd be getting a KeyError there. It's mandated and required by the wsgi spec: https://www.python.org/dev/peps/pep-0333/#environ-variables

**Comment by zhiyong80** [comment] 2016-08-29 00:02
Sorry to get back late. No, it doesn't happen often. It is my first time to see it for the whole month I am using Sentry.

The following is the stack trace, copied from Raw tab:
KeyError: u'REQUEST_METHOD'
  File "raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "sentry/wsgi.py", line 40, in __call__
    response = super(FileWrapperWSGIHandler, self).__call__(environ, start_response)
  File "django/core/handlers/wsgi.py", line 196, in __call__
    request = self.request_class(environ)
  File "django/core/handlers/wsgi.py", line 91, in __init__
    self.method = environ['REQUEST_METHOD'].upper()

It seems very odd to me too. During installation, I simply followed steps on the tutorial page, and passed a bunch of environmental variables. Is it possible I passed some wrong environment value key?

**Comment by mattrobenolt** [comment] 2016-08-29 00:28
Yeah, umm, I definitely don't have an answer for this.

Are you able to share all of the startup information for the container? It's highly unlikely something would affect that.

If it happens again, I'd be more concerned, but this is definitely really odd. I have no idea what would cause that to happen since it's happening outside of anything Sentry or Django would be doing.

**Comment by mattrobenolt** [comment] 2016-08-29 00:31
Are you doing anything to cause uwsgi to run not in http mode with nginx in front? It'd be possible to miss sending `REQUEST_METHOD` in that case. I'm just starting to guess at this point. :)

**Comment by mattrobenolt** [comment] 2016-08-29 00:32
This _seems_ to be related: https://github.com/unbit/uwsgi/issues/715

**Comment by mattrobenolt** [comment] 2016-08-29 00:37
Could you try setting `-e UWSGI_WSGI_ENV_BEHAVIOR=holy` on your container? This is a different environment allocator for uWSGI that says it has better handling for multithreaded applications.

Still odd that we've never seen this ourselves in production for getsentry.com.

**Comment by mattrobenolt** [comment] 2016-08-29 00:47
It seems that this `holy` allocator is definitely recommended over the default `cheat` method. uWSGI just has not made it the default because it doesn't like changing default values/behavior.

I'm going to investigate this a little bit more and test it on getsentry.com. If all is good, I'll make this the default in sentry itself since it definitely is encouraged and more correct.

**Comment by zhiyong80** [comment] 2016-08-29 01:52
Thanks for quick and detailed response. I will try -e UWSGI_WSGI_ENV_BEHAVIOR=holy late tonight.

**Comment by mattrobenolt** [comment] 2016-09-09 15:48
> Just curious, it seems docker/sentry was trying to visit 139.162.209.35 at the time of exception. What's the nature of this communication?

Sorry, I missed this. This is not an IP address that belongs to us. From doing a rDNS lookup, it appears to go to Linode somewhere. My guess is probably related to our external source fetching from your errors.

And I'm going to close this issue since I've yet to hear of this again.

**Closed by mattrobenolt** 2016-09-09 15:48 UTC

**Comment by mattrobenolt** [comment] 2016-09-09 15:49
Oh, and looking at the initial issue, that IP address is the `REMOTE_ADDR` for the request. It's the host that is sending the error to Sentry.

**Comment by MaxDBN** [comment] 2016-11-13 08:29
I'm having the same issue. I'm running sentry for a few days now (without any projects yet)
All of a sudden I have this error in the middle of the night:

**Raw tab:**
```
KeyError: u'REQUEST_METHOD'
  File "raven/middleware.py", line 98, in __call__
    iterable = self.application(environ, start_response)
  File "sentry/wsgi.py", line 41, in __call__
    response = super(FileWrapperWSGIHandler, self).__call__(environ, start_response)
  File "django/core/handlers/wsgi.py", line 196, in __call__
    request = self.request_class(environ)
  File "django/core/handlers/wsgi.py", line 91, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
```

**Comment by mattrobenolt** [comment] 2016-11-13 08:55
@MaxDBN did what I recommend above help at all?

**Comment by MaxDBN** [comment] 2016-11-13 09:23
@mattrobenolt Sorry for the dummy question but how do I set that setting? Hopefully without shutting it off...

**Comment by mattrobenolt** [comment] 2016-11-13 19:48
@MaxDBN It's just passing an environment variable through your `docker run` command. So yes, it'd require stopping and starting the container with new argument passed along.

**Comment by Rukenshia** [comment] 2018-02-17 04:36
Just wanted to mention that I got the same error for IP `172.104.154.84`. I have added the environment variable now.

**Comment by spikerwork** [comment] 2018-02-17 21:24
Yesterday, I have got the same error with remote ip `45.33.6.166`. It is strange, because sentry server used only for few private sites.

**Comment by zeeZ** [comment] 2018-04-11 06:26
This was probably caused by an incorrect HTTP request coming from a random bot. Here's sentry's access log for the most recent one of those errors that popped up:

```
xxx.xxx.xxx.xxx - - [10/Apr/2018:11:17:49 +0000] "- - -" 500 0 "-" "-"
xxx.xxx.xxx.xxx - - [10/Apr/2018:11:17:50 +0000] "GET / HTTP/1.0" 302 437 "-" "-"
xxx.xxx.xxx.xxx - - [10/Apr/2018:11:17:50 +0000] "OPTIONS / HTTP/1.0" 302 437 "-" "-"
xxx.xxx.xxx.xxx - - [10/Apr/2018:11:17:51 +0000] "OPTIONS / RTSP/1.0" 302 437 "-" "-"
xxx.xxx.xxx.xxx - - [10/Apr/2018:11:17:51 +0000] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 301 296 "-" "-"
xxx.xxx.xxx.xxx - - [10/Apr/2018:11:17:52 +0000] "OPTIONS sip:nm SIP/2.0" 404 8176 "-" "-"
```

The first line triggered the internal error
