### ISSUE TITLE
9.1: install fails due to mail.use-tls setting

### ISSUE THREAD

**Issue by acdha** [getsentry/docker-sentry#163] opened 2019-04-05 17:00 UTC
I spun up a fresh install of a custom onbuild deployment of 9.1 and it's failing with this exception:

AssertionError: u'mail.use-tls' cannot be changed at runtime because it is configured on disk

Changing the value of SENTRY_EMAIL_USE_TLS does not appear to have an effect. This is almost the verbatim onbuild module except that it adds a wrapper which populates the environment from AWS SSM values (working around FarGate design limitations).

**Comment by ei-grad** [comment] 2019-04-06 16:15
The similar issue, but with 'mail.from' field. The docker sentry installation procedure is broken.

**Comment by mattrobenolt** [comment] 2019-04-06 16:18
Thanks for bringing his up. I’m going to look into this.

**Comment by ei-grad** [comment] 2019-04-06 16:20
Checked the same process for 9.0 - all is working as expected.

**Comment by acdha** [comment] 2019-04-06 17:33
I was able to work around it by using the regular image now that AWS has shipped secrets management in Fargate but it seems like this should work either way.

**Comment by mafredri** [comment] 2019-04-12 13:14
I had the `mail.from` issue as well. I can only reproduce the issue when creating a superuser account, and upon login Sentry asks to define base url / mail (from) and some other settings. It's not possible to get past this due to the `mail.from` being configured on disk.

Removing the following lines solved the issue:
https://github.com/getsentry/docker-sentry/blob/4b3fad46dbe56285629162e059f4f0e89174b0f9/9.1/sentry.conf.py#L258-L266
https://github.com/getsentry/docker-sentry/blob/4b3fad46dbe56285629162e059f4f0e89174b0f9/9.1/sentry.conf.py#L270

Not sure if all of it was necessary. It's possible only line 270 needed to be removed.

**Comment by dcramer** [comment] 2019-04-14 16:28
I wonder why we're binding default values in docker vs forcing you to configure it via the UI when it's not setup from the environment.. seems backwards from any other way we'd suggest to install it.

**Comment by dcramer** [comment] 2019-04-19 16:42
Will be fixed in 9.1.1 which we're hoping to get out later today.

**Closed by dcramer** 2019-04-19 16:42 UTC

**Comment by rbtellis** [comment] 2019-04-22 21:12
Can this fix be uploaded to Dockerhub? I am trying to use the onpremise docker scripts, but this bug is preventing me from installing. I attempted to build the new docker image, but got a gpg failure.
gpg: Can't check signature: No public key

**Comment by dcramer** [comment] 2019-04-22 21:14
We do not control the speed at which Docker publishes new version:

https://github.com/docker-library/official-images/pull/5772

**Comment by rbtellis** [comment] 2019-04-22 21:20
Ok, thanks for the info!
