### ISSUE TITLE
Track sentry errors with itself

### ISSUE THREAD

**Issue by alexanderadam** [getsentry/docker-sentry#179] opened 2019-06-17 10:04 UTC
Is it possible to track sentry errors with itself?

I just ran into [issue 85](https://github.com/getsentry/docker-sentry/issues/85) / [132](https://github.com/getsentry/docker-sentry/issues/132) and this issue was created on a regular project.
But if I understand this correctly, the cause is a crawler making unsupported requests on sentry, right?

Which got me thinking whether it is possible to track sentry errors within a dedicated sentry project on the same Docker instance.
Because it makes quite sense to track sentry issues in general as well, doesn't it?

**Comment by BYK** [comment] 2019-07-09 09:22
There should be an "internal" project that tracks Sentry's own issues. Btw I'd recommend using the forums for discussions like these in the future: https://forum.sentry.io/c/on-premise

This should make it more visible to other people using Sentry on-premise :)

**Comment by BYK** [comment] 2019-07-09 09:23
Closing as this is not a bug or a feature request we can act on.

**Closed by BYK** 2019-07-09 09:23 UTC
