### ISSUE TITLE
npm install --production --quiet returns exit status 1

### ISSUE THREAD

**Issue by npockrus-bnet** [getsentry/docker-sentry#130] opened 2018-05-01 22:59 UTC
I am trying to build sentry from master so I'm using build-git and I keep getting the following errors:

npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "--production" "--quiet"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package emotion@9.1.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grid-emotion@2.1.0 wants emotion@8
npm ERR! peerinvalid Peer react-emotion@9.1.2 wants emotion@^9.1.2

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/sentry/npm-debug.log
command failed [npm install --production --quiet] via [/usr/src/sentry]
Traceback (most recent call last):
  File "setup.py", line 156, in <module>
    'Topic :: Software Development'
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 99, in run
    self.run_command('build_integration_docs')
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/src/sentry/src/sentry/utils/distutils/commands/base.py", line 186, in run
    self._setup_npm()
  File "/usr/src/sentry/src/sentry/utils/distutils/commands/base.py", line 145, in _setup_npm
    self._run_command(['npm', 'install', '--production', '--quiet'])
  File "/usr/src/sentry/src/sentry/utils/distutils/commands/base.py", line 150, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['npm', 'install', '--production', '--quiet']' returned non-zero exit status 1

I've tried tracing the error back but I don't see where it is coming from. I would appreciate any help!

**Comment by mattrobenolt** [comment] 2018-05-01 23:01
The build from git version is highly out of date, so this whole thing needs to be updated or removed.

**Comment by mattrobenolt** [comment] 2018-06-15 16:52
Dupe of #133

**Closed by mattrobenolt** 2018-06-15 16:52 UTC
